export const FETCH_EVENT = 'FETCH_EVENT';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
export const RETAIN_STATE = 'RETAIN_STATE';
export const SELECT_EVENT = 'SELECT_EVENT';
export const MODIFY_EVENT = 'MODIFY_EVENT';
export const CLEAR_SELECTEVENTS = 'CLEAR_SELECTEVENTS';
